ALTER TABLE "task" ADD COLUMN "number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "task_number_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_number_unique" UNIQUE("number");--> statement-breakpoint

WITH ordered AS (
  SELECT "id", row_number() OVER (ORDER BY "created_at", "id") AS n FROM "task"
)
UPDATE "task" SET "number" = -ordered.n FROM ordered WHERE "task"."id" = ordered."id";--> statement-breakpoint
UPDATE "task" SET "number" = -"number";--> statement-breakpoint
SELECT setval(
  pg_get_serial_sequence('task', 'number'),
  COALESCE((SELECT max("number") FROM "task"), 0) + 1,
  false
);
